aliist = {
  "getVector": {
    "id": "7742969",
    "created": "2014-03-20T19:51:09.333000+00:00",
    "isPub": True,
    "items": [
      {
        "type": "brand",
        "brand": "youtube",
        "brandUrl": "http://www.youtube.com"
      },
      {
        "t": "yt",
        "f": "TWWgQbbPnps",
        "tt": "汪峰《存在》新歌首播版MV",
        "tm": 294,
        "_id": "32790",
        "type": "music",
        "dbIndex": 0,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 0
      },
      {
        "t": "yt",
        "f": "0oZn1M50Uw0",
        "tt": "《北京北京》汪峰（词曲唱）",
        "tm": 378,
        "_id": "64665",
        "type": "music",
        "dbIndex": 1,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 1
      },
      {
        "t": "yt",
        "f": "lgLF1eMF-zI",
        "tt": "玖壹壹-再會中港路",
        "tm": 205,
        "_id": "22257887",
        "type": "music",
        "dbIndex": 2,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 2
      },
      {
        "t": "yt",
        "f": "fYrBo8XEssE",
        "tt": "動力火車 Power Station [ 彩虹 Rainbow ] Official Music Video",
        "tm": 278,
        "_id": "7361875",
        "type": "music",
        "dbIndex": 3,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 3
      },
      {
        "t": "yt",
        "f": "GXCqD01A8Ak",
        "tt": "動力火車 Power Station [ 莫忘初衷 Never Alone ] Official Music Video",
        "tm": 355,
        "_id": "7835717",
        "type": "music",
        "dbIndex": 4,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 4
      },
      {
        "t": "yt",
        "f": "1rSjGYhaM8k",
        "tt": "動力火車 Power Station [ 繼續轉動 Spinning] Official Music Video",
        "tm": 214,
        "_id": "260489",
        "type": "music",
        "dbIndex": 5,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 5
      },
      {
        "t": "yt",
        "f": "m2z8G6iHXSw",
        "tt": "動力火車《明天的明天的明天》",
        "tm": 406,
        "_id": "24070721",
        "type": "music",
        "dbIndex": 6,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 6
      },
      {
        "t": "yt",
        "f": "MuKzdZK7lZo",
        "tt": "Jessie J - Flashlight (Lyrics)",
        "tm": 222,
        "_id": "29467717",
        "type": "music",
        "dbIndex": 7,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 7
      },
      {
        "t": "yt",
        "f": "Jf4x3INvpGc",
        "tt": "Price tag - Jessie J lyrics",
        "tm": 218,
        "_id": "12055724",
        "type": "music",
        "dbIndex": 8,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 8
      },
      {
        "t": "yt",
        "f": "H0Eu1syELno",
        "tt": "郁可唯 Yisa Yu&林凡 Freya Lim【聽你說】Official Music Video",
        "tm": 262,
        "_id": "102364",
        "type": "music",
        "dbIndex": 9,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 9
      },
      {
        "t": "yt",
        "f": "9c8ArimadEc",
        "tt": "彭青-我只能愛你(射鵰英雄傳插曲)-高清原創版",
        "tm": 395,
        "_id": "90699",
        "type": "music",
        "dbIndex": 10,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 10
      },
      {
        "t": "yt",
        "f": "YLXxPMikmTE",
        "tt": "杨坤《月亮可以代表我的心》",
        "tm": 313,
        "_id": "21886712",
        "type": "music",
        "dbIndex": 11,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 11
      },
      {
        "t": "yt",
        "f": "4OqXWzekVw4",
        "tt": "G.E.M. 鄧紫棋 - 喜歡你 Official MV [HD]",
        "tm": 270,
        "_id": "26454074",
        "type": "music",
        "dbIndex": 12,
        "action": "editMusic",
        "currentListeningCount": 8,
        "musicIndex": 12
      },
      {
        "t": "yt",
        "f": "ijLLmE_sFkY",
        "tt": "李榮浩 Ronghao Li - 喜劇之王 King of Comedy (Official 高畫質 HD 官方完整版 MV)",
        "tm": 262,
        "_id": "27418375",
        "type": "music",
        "dbIndex": 13,
        "action": "editMusic",
        "currentListeningCount": 5,
        "musicIndex": 13
      },
      {
        "t": "yt",
        "f": "mGeiABBB5f8",
        "tt": "G.E.M. \"泡沫\"  \"BUBBLE\" [HD] 官方MV 鄧紫棋",
        "tm": 274,
        "_id": "4682917",
        "type": "music",
        "dbIndex": 14,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 14
      },
      {
        "t": "yt",
        "f": "j3AW1uKj2aE",
        "tt": "關喆 Grady - 想你的夜 (未眠版) Miss You Tonight (Official 高畫質 HD 官方完整版 MV)",
        "tm": 287,
        "_id": "26560917",
        "type": "music",
        "dbIndex": 15,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 15
      },
      {
        "t": "yt",
        "f": "wdypZWuoKvQ",
        "tt": "李榮浩 - 李白 (官方版MV)",
        "tm": 276,
        "_id": "26088988",
        "type": "music",
        "dbIndex": 16,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 16
      },
      {
        "t": "yt",
        "f": "Y7ix6RITXM0",
        "tt": "Maroon 5 - Maps (Lyric Video)",
        "tm": 189,
        "_id": "25912092",
        "type": "music",
        "dbIndex": 17,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 17
      },
      {
        "t": "yt",
        "f": "b1SRjGmgA54",
        "tt": "任賢齊 Richie Jen 【傷心太平洋 The Sad Pacific】1998台視「神鵰俠侶」片尾曲 Official Music Video",
        "tm": 265,
        "_id": "48569",
        "type": "music",
        "dbIndex": 18,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 18
      },
      {
        "t": "yt",
        "f": "hQMRGsteyRc",
        "tt": "任賢齊 Richie Jen【我是一隻魚 I’m a fish】Official Music Video",
        "tm": 255,
        "_id": "66853",
        "type": "music",
        "dbIndex": 19,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 19
      },
      {
        "t": "yt",
        "f": "ZSWeurc1yMw",
        "tt": "任賢齊 Richie Jen【心太軟 Too softhearted】Official Music Video",
        "tm": 353,
        "_id": "131415",
        "type": "music",
        "dbIndex": 20,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 20
      },
      {
        "t": "yt",
        "f": "nZ18FkLNUxw",
        "tt": "任賢齊 Richie Jen【兩極】中視「風雲II」主題曲 Official Music Video",
        "tm": 264,
        "_id": "139791",
        "type": "music",
        "dbIndex": 21,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 21
      },
      {
        "t": "yt",
        "f": "yGoHsTV6QrE",
        "tt": "伍佰 Wu Bai&China Blue【被動 Passive】Official Music Video",
        "tm": 260,
        "_id": "53080",
        "type": "music",
        "dbIndex": 22,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 22
      },
      {
        "t": "yt",
        "f": "ZpxoYKrC1dY",
        "tt": "伍佰 - 如果這都不算愛 (live)",
        "tm": 288,
        "_id": "624893",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 23,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 23
      },
      {
        "t": "yt",
        "f": "x-pCAngjeOw",
        "tt": "[avex官方]伍佰 & China Blue 淚橋(MV完整版)",
        "tm": 223,
        "_id": "6830307",
        "type": "music",
        "dbIndex": 24,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 24
      },
      {
        "t": "yt",
        "f": "ObSPLQ-1fJI",
        "tt": "伍佰 Wu Bai&China Blue【樹枝孤鳥 Lonely tree,lonely bird】Official Music Video",
        "tm": 288,
        "_id": "46853",
        "type": "music",
        "dbIndex": 25,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 25
      },
      {
        "t": "yt",
        "f": "6BtPKWI-uOs",
        "tt": "伍佰  鋼鐵男子",
        "tm": 198,
        "_id": "10785",
        "type": "music",
        "dbIndex": 26,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 26
      },
      {
        "t": "yt",
        "f": "jPu3u8kfxCw",
        "tt": "伍佰 Wu Bai&China Blue【世界第一等】Official Music Video",
        "tm": 238,
        "_id": "53098",
        "type": "music",
        "dbIndex": 27,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 27
      },
      {
        "t": "yt",
        "f": "MU7JmTT9oEw",
        "tt": "吳宗憲 - 你比從前快樂",
        "tm": 230,
        "_id": "1258696",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 28,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 28
      },
      {
        "t": "yt",
        "f": "EaK7Tog-xGg",
        "tt": "李玖哲~我會好好過 MV",
        "tm": 246,
        "_id": "36986",
        "type": "music",
        "dbIndex": 29,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 29
      },
      {
        "t": "yt",
        "f": "fVtmLnmkrp4",
        "tt": "李玖哲Nicky Lee-想太多Think Too Much-完整版MV.wmv",
        "tm": 270,
        "_id": "5021475",
        "type": "music",
        "dbIndex": 30,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 30
      },
      {
        "t": "yt",
        "f": "ogLOzLQcbkQ",
        "tt": "李玖哲 Nicky Lee 不，完美Not   Perfect 完整版MV",
        "tm": 249,
        "_id": "861630",
        "type": "music",
        "dbIndex": 31,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 31
      },
      {
        "t": "yt",
        "f": "rVEMTxg_LrU",
        "tt": "Jonathan Lee李宗盛 [ 山丘 ] Official Music Video",
        "tm": 406,
        "_id": "13739055",
        "type": "music",
        "dbIndex": 32,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 32
      },
      {
        "t": "yt",
        "f": "nLU0twQ2eb4",
        "tt": "汪峰-春天里mv(HQ)",
        "tm": 283,
        "_id": "19558",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 33,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 33
      },
      {
        "t": "yt",
        "f": "kdWQaecFyyo",
        "tt": "汪峰 — 当我想你的时候",
        "tm": 271,
        "_id": "32784",
        "type": "music",
        "dbIndex": 34,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 34
      },
      {
        "t": "yt",
        "f": "XBBsVn2EW6s",
        "tt": "汪峰 -《生來彷徨》- 生來彷徨",
        "tm": 270,
        "_id": "21143287",
        "type": "music",
        "dbIndex": 35,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 35
      },
      {
        "t": "yt",
        "f": "wt0RKW3aC84",
        "tt": "Jay Chou 周杰倫【給我一首歌的時間 Give me the time of a song】-Official Music Video",
        "tm": 254,
        "_id": "7515083",
        "type": "music",
        "dbIndex": 36,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 36
      },
      {
        "t": "yt",
        "f": "H7hpK6cm-6k",
        "tt": "周杰倫 Jay Chou【開不了口 I Find It Hard To Say】Official MV",
        "tm": 293,
        "_id": "4027172",
        "type": "music",
        "dbIndex": 37,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 37
      },
      {
        "t": "yt",
        "f": "DYptgVvkVLQ",
        "tt": "Jay Chou周杰倫【晴天 Sunny Day】-Official Music Video",
        "tm": 319,
        "_id": "7997291",
        "type": "music",
        "dbIndex": 38,
        "action": "editMusic",
        "currentListeningCount": 7,
        "musicIndex": 38
      },
      {
        "t": "yt",
        "f": "4j0Fgmsxr-o",
        "tt": "周杰倫 Jay Chou【超人不會飛 Superman Can't Fly】Official MV",
        "tm": 303,
        "_id": "614838",
        "type": "music",
        "dbIndex": 39,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 39
      },
      {
        "t": "yt",
        "f": "QwUH0xyEcKc",
        "tt": "周杰倫 - 安靜 HD",
        "tm": 330,
        "_id": "20892",
        "type": "music",
        "dbIndex": 40,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 40
      },
      {
        "t": "yt",
        "f": "fgPetg6HEEA",
        "tt": "周杰倫Jay - 你怎麼連話都說不清楚",
        "tm": 230,
        "_id": "584227",
        "type": "music",
        "dbIndex": 41,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 41
      },
      {
        "t": "yt",
        "f": "s-VFpsrbWLk",
        "tt": "Jay Chou 周杰倫【我不配 Not Good Enough For You】-Official Music Video",
        "tm": 318,
        "_id": "7629441",
        "type": "music",
        "dbIndex": 42,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 42
      },
      {
        "t": "yt",
        "f": "CmVAQbnpCHg",
        "tt": "稻香 MV  - 周杰倫 Jay Chou [HQ高清]",
        "tm": 224,
        "_id": "30817",
        "type": "music",
        "dbIndex": 43,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 43
      },
      {
        "t": "yt",
        "f": "8Q9SVzhwjus",
        "tt": "周杰倫&Lara - 珊瑚海 HD",
        "tm": 262,
        "_id": "25154",
        "type": "music",
        "dbIndex": 44,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 44
      },
      {
        "t": "yt",
        "f": "tlmMko3fjsc",
        "tt": "林志炫   單身情歌",
        "tm": 265,
        "_id": "955819",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 45,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 45
      },
      {
        "t": "yt",
        "f": "EwaS8-HWCqs",
        "tt": "林志炫．浮誇(國語版)",
        "tm": 292,
        "_id": "126991",
        "type": "music",
        "dbIndex": 46,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 46
      },
      {
        "t": "yt",
        "f": "PRdMW6a4gpI",
        "tt": "林志炫 - 愛情釀的酒",
        "tm": 299,
        "_id": "861861",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 47,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 47
      },
      {
        "t": "yt",
        "f": "I_xbqaA49bI",
        "tt": "优客李林 - 认错",
        "tm": 275,
        "_id": "230287",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 48,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 48
      },
      {
        "t": "yt",
        "f": "jmisbiXtlas",
        "tt": "(HD)林志炫--花香",
        "tm": 264,
        "_id": "15614758",
        "type": "music",
        "dbIndex": 49,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 49
      },
      {
        "t": "yt",
        "f": "eg7XjwGnI3Y",
        "tt": "林俊傑-簡簡單單MV",
        "tm": 247,
        "_id": "18955",
        "type": "music",
        "dbIndex": 50,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 50
      },
      {
        "t": "yt",
        "f": "1TlrGVyFOYU",
        "tt": "迪克牛仔 - 有多少愛可以重來",
        "tm": 297,
        "_id": "18383",
        "type": "music",
        "dbIndex": 51,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 51
      },
      {
        "t": "yt",
        "f": "HLzngD6H36E",
        "tt": "老爹 by 迪克牛仔&弦子",
        "tm": 234,
        "_id": "45179",
        "type": "music",
        "dbIndex": 52,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 52
      },
      {
        "t": "yt",
        "f": "0ivNMQauscc",
        "tt": "范逸臣-放生  官方MV",
        "tm": 269,
        "_id": "66743",
        "type": "music",
        "dbIndex": 53,
        "action": "editMusic",
        "currentListeningCount": 23,
        "musicIndex": 53
      },
      {
        "t": "yt",
        "f": "dI5zpKaNR84",
        "tt": "范逸臣-I BELIEVE  官方MV",
        "tm": 289,
        "_id": "57211",
        "type": "music",
        "dbIndex": 54,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 54
      },
      {
        "t": "yt",
        "f": "CA4Rg92qs-s",
        "tt": "信 Shin [ 反正我信了 Whatever, I just believe in ] Official Music Video",
        "tm": 285,
        "_id": "28649260",
        "type": "music",
        "dbIndex": 55,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 55
      },
      {
        "t": "yt",
        "f": "7QcCPmXlcqY",
        "tt": "亂彈阿翔 - 完美落地 - 電影〈翻滾吧！阿信〉主題曲",
        "tm": 284,
        "_id": "25253",
        "type": "music",
        "dbIndex": 56,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 56
      },
      {
        "t": "yt",
        "f": "xl7enIAM4Go",
        "tt": "楊培安 - 我相信",
        "tm": 245,
        "_id": "7567172",
        "type": "music",
        "dbIndex": 57,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 57
      },
      {
        "t": "yt",
        "f": "J3GHPH2E0mg",
        "tt": "楊培安 - 痛也不說出口的我",
        "tm": 276,
        "_id": "6617387",
        "type": "music",
        "dbIndex": 58,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 58
      },
      {
        "t": "yt",
        "f": "EScKfUivHis",
        "tt": "制造浪漫-郑中基&陈慧琳",
        "tm": 285,
        "_id": "101609",
        "type": "music",
        "dbIndex": 59,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 59
      },
      {
        "t": "yt",
        "f": "WbaDEns-YTM",
        "tt": "■刘德华　忘情水",
        "tm": 291,
        "_id": "15802",
        "type": "music",
        "dbIndex": 60,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 60
      },
      {
        "t": "yt",
        "f": "3RVSHJPCLFo",
        "tt": "劉德華-謝謝你的愛(國語版)",
        "tm": 258,
        "_id": "18662",
        "type": "music",
        "dbIndex": 61,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 61
      },
      {
        "t": "yt",
        "f": "PwSQQoWqeBs",
        "tt": "Beyond 05: 光輝歲月",
        "tm": 319,
        "_id": "11678",
        "type": "music",
        "dbIndex": 62,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 62
      },
      {
        "t": "yt",
        "f": "qu_FSptjRic",
        "tt": "BEYOND【海闊天空】Official Music Video",
        "tm": 318,
        "_id": "277618",
        "type": "music",
        "dbIndex": 63,
        "action": "editMusic",
        "currentListeningCount": 6,
        "musicIndex": 63
      },
      {
        "t": "yt",
        "f": "QGJuMBdaqIw",
        "tt": "Katy Perry - Firework (Official)",
        "tm": 234,
        "_id": "21191991",
        "type": "music",
        "dbIndex": 64,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 64
      },
      {
        "t": "yt",
        "f": "n0XguJCwIVc",
        "tt": "Call Me Maybe by Carly Rae Jepsen Lyrics",
        "tm": 208,
        "_id": "745369",
        "type": "music",
        "dbIndex": 65,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 65
      },
      {
        "t": "yt",
        "f": "suRsxpoAc5w",
        "tt": "Moves Like Jagger - Maroon 5 featuring Christina Aguilera",
        "tm": 203,
        "_id": "165",
        "type": "music",
        "dbIndex": 66,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 66
      },
      {
        "t": "yt",
        "f": "_EDjh8KUVHs",
        "tt": "What Makes You Beautiful-One Direction (w/lyrics, pics, names)",
        "tm": 201,
        "_id": "8603791",
        "statusCode": 2,
        "type": "music",
        "dbIndex": 67,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 67
      },
      {
        "t": "yt",
        "f": "9cyekybKA74",
        "tt": "马嘉轩 - 《认错》官方MV",
        "tm": 274,
        "_id": "149612",
        "type": "music",
        "dbIndex": 68,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 68
      },
      {
        "t": "yt",
        "f": "ETTUAwUSGpg",
        "tt": "[avex官方]信 告別的時代(MV完整版)",
        "tm": 295,
        "_id": "6739943",
        "type": "music",
        "dbIndex": 69,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 69
      },
      {
        "t": "yt",
        "f": "iYxKyE6bu_8",
        "tt": "《我是歌手》彭佳慧-相見恨晚 (優化版)",
        "tm": 266,
        "_id": "8186844",
        "type": "music",
        "dbIndex": 70,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 70
      },
      {
        "t": "yt",
        "f": "_EG0qkiG6Rs",
        "tt": "20130315【我是歌手】彭佳慧 《走在紅毯那一天》",
        "tm": 279,
        "_id": "7494597",
        "type": "music",
        "dbIndex": 71,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 71
      },
      {
        "t": "yt",
        "f": "p0mLoOMJOZU",
        "tt": "龍梅子  -  Hold不住的愛【 電視劇片尾曲 】【 賴漢的幸福指數 】【 高清 】",
        "tm": 233,
        "_id": "27651749",
        "type": "music",
        "dbIndex": 72,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 72
      },
      {
        "t": "yt",
        "f": "-_ygYrXgdhg",
        "tt": "龍梅子&老貓---最右",
        "tm": 221,
        "_id": "30216020",
        "type": "music",
        "dbIndex": 73,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 73
      },
      {
        "t": "yt",
        "f": "F5FlN-NBGo8",
        "tt": "[avex官方] A-Lin 給我一個理由忘記 (MV完整版)",
        "tm": 287,
        "_id": "11022",
        "type": "music",
        "dbIndex": 74,
        "action": "editMusic",
        "currentListeningCount": 6,
        "musicIndex": 74
      },
      {
        "t": "yt",
        "f": "XbZbW983N1Y",
        "tt": "[avex官方MV] A-Lin 分手需要練習的 (MV完整版)",
        "tm": 427,
        "_id": "10723",
        "type": "music",
        "dbIndex": 75,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 75
      },
      {
        "t": "yt",
        "f": "e-TU7EZDESk",
        "tt": "[avex官方] A-Lin 大大的擁抱 (MV完整版)",
        "tm": 241,
        "_id": "10876",
        "type": "music",
        "dbIndex": 76,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 76
      },
      {
        "t": "yt",
        "f": "MEVY19A70F0",
        "tt": "[avex官方]A-Lin P.S 我愛你 (MV完整版)",
        "tm": 258,
        "_id": "5407805",
        "type": "music",
        "dbIndex": 77,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 77
      },
      {
        "t": "yt",
        "f": "lmFlqWPzl-E",
        "tt": "[avex官方] A-Lin 失戀無罪 (MV完整版)",
        "tm": 243,
        "_id": "5380129",
        "type": "music",
        "dbIndex": 78,
        "action": "editMusic",
        "currentListeningCount": 5,
        "musicIndex": 78
      },
      {
        "t": "yt",
        "f": "T-XFIPKmhww",
        "tt": "Della丁噹 [ 洋蔥 ] MV官方高清完整版",
        "tm": 311,
        "_id": "10909",
        "type": "music",
        "dbIndex": 79,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 79
      },
      {
        "t": "yt",
        "f": "CqlnZuXQpy8",
        "tt": "Della丁噹【不是你的錯Not Your Fault】MV官方完整版-三立[真愛找麻煩]插曲",
        "tm": 221,
        "_id": "32084",
        "type": "music",
        "dbIndex": 80,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 80
      },
      {
        "t": "yt",
        "f": "QKb30DgwZ7Y",
        "tt": "丁噹 [ 我愛他 ] MV官方完整版",
        "tm": 294,
        "_id": "17750",
        "type": "music",
        "dbIndex": 81,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 81
      },
      {
        "t": "yt",
        "f": "FdjR-AMz50c",
        "tt": "Della丁噹 [ 我是一隻小小鳥 ] MV官方完整高清版",
        "tm": 289,
        "_id": "21920",
        "type": "music",
        "dbIndex": 82,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 82
      },
      {
        "t": "yt",
        "f": "pi3_EjJz1ps",
        "tt": "江蕙 阿杜 夢中的情話",
        "tm": 291,
        "_id": "5110093",
        "type": "music",
        "dbIndex": 83,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 83
      },
      {
        "t": "yt",
        "f": "ZSfj1lDHSEw",
        "tt": "那英 - 夢一場 [MV]",
        "tm": 231,
        "_id": "504404",
        "type": "music",
        "dbIndex": 84,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 84
      },
      {
        "t": "yt",
        "f": "HJ8BOEr4Ggs",
        "tt": "那英 - 征服 MV",
        "tm": 287,
        "_id": "94593",
        "type": "music",
        "dbIndex": 85,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 85
      },
      {
        "t": "yt",
        "f": "KheDK8lO0Qc",
        "tt": "那英 - 白天不懂夜的黑 (官方版MV)",
        "tm": 229,
        "_id": "41572",
        "type": "music",
        "dbIndex": 86,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 86
      },
      {
        "t": "yt",
        "f": "XfI5DwNj9oc",
        "tt": "李佳薇 煎熬(Jess Lee - Suffering) 完整版MV -華納official HQ官方版MV",
        "tm": 371,
        "_id": "11743",
        "type": "music",
        "dbIndex": 87,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 87
      },
      {
        "t": "yt",
        "f": "b14RrwuEPEk",
        "tt": "林凡 Freya Lim【歲月這把刀 Time doesn't heal】三立優質偶像劇 《女人30情定水舞間》片尾曲 Official Music Video",
        "tm": 330,
        "_id": "25031967",
        "type": "music",
        "dbIndex": 88,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 88
      },
      {
        "t": "yt",
        "f": "hbO9OwRsBR0",
        "tt": "林憶蓮-至少還有你 (HD)",
        "tm": 275,
        "_id": "1065222",
        "type": "music",
        "dbIndex": 89,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 89
      },
      {
        "t": "yt",
        "f": "ZD57Fv_V74s",
        "tt": "林憶蓮 Sandy Lam【為你我受冷風吹 Suffer for you】Official Music Video",
        "tm": 261,
        "_id": "56396",
        "type": "music",
        "dbIndex": 90,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 90
      },
      {
        "t": "yt",
        "f": "HenAli59n6A",
        "tt": "林憶蓮 Sandy Lam【夢醒時分 Dream to awakening】Official Music Video",
        "tm": 213,
        "_id": "1011665",
        "type": "music",
        "dbIndex": 91,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 91
      },
      {
        "t": "yt",
        "f": "P9Acp_P6HiU",
        "tt": "KTV孫淑媚 癡情歌 02 愛是一種負擔",
        "tm": 309,
        "_id": "1082525",
        "type": "music",
        "dbIndex": 92,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 92
      },
      {
        "t": "yt",
        "f": "9nxnJdEKo58",
        "tt": "孫淑媚-父母的心聲【官方完整MV版】",
        "tm": 319,
        "_id": "117056",
        "type": "music",
        "dbIndex": 93,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 93
      },
      {
        "t": "yt",
        "f": "E8QoYoWrWQQ",
        "tt": "孫淑媚-痴情歌【官方完整MV版】",
        "tm": 269,
        "_id": "57135",
        "type": "music",
        "dbIndex": 94,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 94
      },
      {
        "t": "yt",
        "f": "DOOUiKvmv_M",
        "tt": "孫燕姿--開始懂了 live",
        "tm": 181,
        "_id": "5460",
        "type": "music",
        "dbIndex": 95,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 95
      },
      {
        "t": "yt",
        "f": "xOtBMnlI3Mk",
        "tt": "張清芳-《無人熟識 》- (豐華唱片official 官方完整版MV)",
        "tm": 274,
        "_id": "121663",
        "type": "music",
        "dbIndex": 96,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 96
      },
      {
        "t": "yt",
        "f": "V2hLoSVFwQQ",
        "tt": "辦不到 - 張靚穎 Feat. 大嘴巴",
        "tm": 195,
        "_id": "351750",
        "type": "music",
        "dbIndex": 97,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 97
      },
      {
        "t": "yt",
        "f": "jik6kfmtm_I",
        "tt": "蔣嘉瑩 - 假如真的再有約會MV",
        "tm": 263,
        "_id": "87224",
        "type": "music",
        "dbIndex": 98,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 98
      },
      {
        "t": "yt",
        "f": "TkO5FAy5PZE",
        "tt": "信樂團 - 不會消失的夜晚",
        "tm": 293,
        "_id": "31488",
        "type": "music",
        "dbIndex": 99,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 99
      },
      {
        "t": "yt",
        "f": "Vl75aVHhNxU",
        "tt": "Sunshine Girl - moumoon.wmv",
        "tm": 228,
        "_id": "6267167",
        "type": "music",
        "dbIndex": 100,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 100
      },
      {
        "t": "yt",
        "f": "qfOV7cwyJrU",
        "tt": "原來愛情這麼傷",
        "tm": 275,
        "_id": "18369",
        "type": "music",
        "dbIndex": 101,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 101
      },
      {
        "t": "yt",
        "f": "WwerHJQ-77I",
        "tt": "梁咏琪 - 胆小鬼 MV",
        "tm": 266,
        "_id": "313134",
        "type": "music",
        "dbIndex": 102,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 102
      },
      {
        "t": "yt",
        "f": "Dw-R85AcN_w",
        "tt": "萬芳 Wan Fang【新不了情 New everlasting love】Official Music Video",
        "tm": 266,
        "_id": "4477232",
        "type": "music",
        "dbIndex": 103,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 103
      },
      {
        "t": "yt",
        "f": "JJhlRIN90YY",
        "tt": "伍佰 Wu Bai&China Blue&萬芳 Wan Fang【愛情限時批 Express love letter】Official Music Video",
        "tm": 224,
        "_id": "53083",
        "type": "music",
        "dbIndex": 104,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 104
      },
      {
        "t": "yt",
        "f": "ATeI8-tnJfo",
        "tt": "黃乙玲 - 愛情這歹找",
        "tm": 270,
        "_id": "786085",
        "type": "music",
        "dbIndex": 105,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 105
      },
      {
        "t": "yt",
        "f": "tNo3LuZXA1w",
        "tt": "黃妃 Huang Fei【追追追】Official Music Video",
        "tm": 282,
        "_id": "1457573",
        "type": "music",
        "dbIndex": 106,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 106
      },
      {
        "t": "yt",
        "f": "wDuymwTln7A",
        "tt": "神鵰俠侶主題曲《天下無雙》MV",
        "tm": 316,
        "_id": "29238",
        "type": "music",
        "dbIndex": 107,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 107
      },
      {
        "t": "yt",
        "f": "ull58YWDots",
        "tt": "一生所愛-盧冠廷",
        "tm": 283,
        "_id": "29236",
        "type": "music",
        "dbIndex": 108,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 108
      },
      {
        "t": "yt",
        "f": "ltRJXN4YSbY",
        "tt": "龍劭華 孤單.mpg",
        "tm": 251,
        "_id": "755534",
        "type": "music",
        "dbIndex": 109,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 109
      },
      {
        "t": "yt",
        "f": "hCfFFZfxUVw",
        "tt": "Bing Bing Bing",
        "tm": 258,
        "_id": "2485524",
        "type": "music",
        "dbIndex": 110,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 110
      },
      {
        "t": "yt",
        "f": "VI9XWPkt_vo",
        "tt": "謝謝你的愛1999",
        "tm": 204,
        "_id": "49507",
        "type": "music",
        "dbIndex": 111,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 111
      },
      {
        "t": "yt",
        "f": "TzgnsVjeXtY",
        "tt": "迪克牛仔酒後心聲",
        "tm": 350,
        "_id": "785850",
        "type": "music",
        "dbIndex": 112,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 112
      },
      {
        "t": "yt",
        "f": "FK_J5dee-14",
        "tt": "韓晶－不要用我的爱來傷害我",
        "tm": 229,
        "_id": "808154",
        "type": "music",
        "dbIndex": 113,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 113
      },
      {
        "t": "yt",
        "f": "8uk8TxE2ZoM",
        "tt": "MC HotDog 熱狗 feat.蛋堡 Soft Lipa【不吃早餐才是一件很嘻哈的事 No Breakfast for Hip-Hoppers】Official Music Video",
        "tm": 274,
        "_id": "1018044",
        "type": "music",
        "dbIndex": 114,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 114
      },
      {
        "t": "yt",
        "f": "PIZ3p8LTDaA",
        "tt": "MC HotDog 熱狗 feat.張震嶽 A-Yue&關穎 Terri Kwan【嗨嗨人生 High High Life】Official Music Video",
        "tm": 279,
        "_id": "387709",
        "type": "music",
        "dbIndex": 115,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 115
      },
      {
        "t": "yt",
        "f": "NQon71jCo0M",
        "tt": "MC HotDog 熱狗 feat.張震嶽 A-Yue【離開】Official Music Video HD (導演版)",
        "tm": 326,
        "_id": "76640",
        "type": "music",
        "dbIndex": 116,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 116
      },
      {
        "t": "yt",
        "f": "8uk8TxE2ZoM",
        "tt": "MC HotDog 熱狗 feat.蛋堡 Soft Lipa【不吃早餐才是一件很嘻哈的事 No Breakfast for Hip-Hoppers】Official Music Video",
        "tm": 274,
        "_id": "1018044",
        "type": "music",
        "dbIndex": 117,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 117
      },
      {
        "t": "yt",
        "f": "mrqKvu-rqIc",
        "tt": "MC HotDog 熱狗【差不多先生】Official Music Video",
        "tm": 299,
        "_id": "133630",
        "type": "music",
        "dbIndex": 118,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 118
      },
      {
        "t": "yt",
        "f": "FZFcHm9QI6o",
        "tt": "吳雨霏-生生世世愛(仙劍奇俠傳三片頭曲)-DVD原創高清版",
        "tm": 300,
        "_id": "99647",
        "type": "music",
        "dbIndex": 119,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 119
      },
      {
        "t": "yt",
        "f": "vdxubNSPVhk",
        "tt": "張芸京-偏愛(仙劍奇俠傳三插曲)-DVD官方高清版",
        "tm": 455,
        "_id": "76521",
        "type": "music",
        "dbIndex": 120,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 120
      },
      {
        "t": "yt",
        "f": "zNeBhsPbgu8",
        "tt": "青鳥飛魚-此生不換(仙劍奇俠傳三插曲)-DVD原創高清版",
        "tm": 555,
        "_id": "76529",
        "type": "music",
        "dbIndex": 121,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 121
      },
      {
        "t": "yt",
        "f": "nUg3InLFbnM",
        "tt": "鄭中基-答應不愛你(仙劍奇俠傳三插曲)-DVD原創高清版",
        "tm": 440,
        "_id": "88255",
        "type": "music",
        "dbIndex": 122,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 122
      },
      {
        "t": "yt",
        "f": "e-ORhEE9VVg",
        "tt": "Taylor Swift - Blank Space",
        "tm": 273,
        "_id": "27425228",
        "type": "music",
        "dbIndex": 123,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 123
      },
      {
        "t": "yt",
        "f": "nG_c_Ap1jsk",
        "tt": "謝霆鋒 Nicholas Tse《281公里(國)》Official 官方完整版 [首播] [MV]",
        "tm": 272,
        "_id": "6566475",
        "type": "music",
        "dbIndex": 124,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 124
      },
      {
        "t": "yt",
        "f": "trQQRc4Uvlw",
        "tt": "Katy Perry - Teenage Dream » Official Video.flv",
        "tm": 236,
        "_id": "3176523",
        "statusCode": 3,
        "type": "music",
        "dbIndex": 125,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 125
      },
      {
        "t": "yt",
        "f": "FRQd9WZI6Fg",
        "tt": "關喆 - 想你的夜 KTV",
        "tm": 298,
        "_id": "5618286",
        "type": "music",
        "dbIndex": 126,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 126
      },
      {
        "t": "yt",
        "f": "906N7VJvPzA",
        "tt": "Jamie N Commons - All Along The Watchtower (Alex Da Kid Remix) FULL SONG",
        "tm": 208,
        "_id": "24987915",
        "type": "music",
        "dbIndex": 127,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 127
      },
      {
        "t": "yt",
        "f": "7cLlnCzZHo8",
        "tt": "Shiny 姚亦晴 [牆] 官方HD MV",
        "tm": 238,
        "_id": "26875500",
        "type": "music",
        "dbIndex": 128,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 128
      },
      {
        "t": "yt",
        "f": "MH74E4YFHWI",
        "tt": "詹雅雯【人生公路】Official Music Video",
        "tm": 286,
        "_id": "28680017",
        "type": "music",
        "dbIndex": 129,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 129
      },
      {
        "t": "yt",
        "f": "ull58YWDots",
        "tt": "一生所愛-盧冠廷",
        "tm": 283,
        "_id": "29236",
        "type": "music",
        "dbIndex": 130,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 130
      },
      {
        "t": "yt",
        "f": "e-ORhEE9VVg",
        "tt": "Taylor Swift - Blank Space",
        "tm": 273,
        "_id": "27425228",
        "type": "music",
        "dbIndex": 131,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 131
      },
      {
        "t": "yt",
        "f": "kdWQaecFyyo",
        "tt": "汪峰 — 当我想你的时候",
        "tm": 271,
        "_id": "32784",
        "type": "music",
        "dbIndex": 132,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 132
      },
      {
        "t": "yt",
        "f": "ft-D_5OmsRY",
        "tt": "汪峰 -《怒放的生命》- 怒放的生命",
        "tm": 276,
        "_id": "7544751",
        "type": "music",
        "dbIndex": 133,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 133
      },
      {
        "t": "yt",
        "f": "Hv5j-FpF1yg",
        "tt": "宋冬野   05 斑馬，斑馬",
        "tm": 254,
        "_id": "15143775",
        "type": "music",
        "dbIndex": 134,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 134
      },
      {
        "t": "yt",
        "f": "Al1yElDgc-A",
        "tt": "張婧懿 - 斑馬斑馬 (完整版)",
        "tm": 215,
        "_id": "27328002",
        "type": "music",
        "dbIndex": 135,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 135
      },
      {
        "t": "yt",
        "f": "SMRs61AOduE",
        "tt": "♫ Celine Dion ► To Love You More ♫",
        "tm": 329,
        "_id": "94625",
        "type": "music",
        "dbIndex": 136,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 136
      },
      {
        "t": "yt",
        "f": "OPf0YbXqDm0",
        "tt": "Mark Ronson - Uptown Funk ft. Bruno Mars (Official Video)",
        "tm": 271,
        "_id": "27518358",
        "type": "music",
        "dbIndex": 137,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 137
      },
      {
        "t": "yt",
        "f": "0HDdjwpPM3Y",
        "tt": "Jessie J, Ariana Grande, Nicki Minaj - Bang Bang ft. Ariana Grande, Nicki Minaj",
        "tm": 263,
        "_id": "26558750",
        "type": "music",
        "dbIndex": 138,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 138
      },
      {
        "t": "yt",
        "f": "vBbHWX32pWk",
        "tt": "李圣杰、张玉华 - 是你决定我的伤心_KTV(HQ_高清)MV",
        "tm": 290,
        "_id": "60376",
        "type": "music",
        "dbIndex": 139,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 139
      },
      {
        "t": "yt",
        "f": "2YUiWMqo18Y",
        "tt": "彭佳慧 - 喜歡兩個人",
        "tm": 334,
        "_id": "9110652",
        "type": "music",
        "dbIndex": 140,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 140
      },
      {
        "t": "yt",
        "f": "N2d9vPacdmw",
        "tt": "莫文蔚 Karen Mok【盛夏的果實】Official Music Video",
        "tm": 264,
        "_id": "74079",
        "type": "music",
        "dbIndex": 141,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 141
      },
      {
        "t": "yt",
        "f": "52lyuJp78pY",
        "tt": "郁可唯 - 時間煮雨 (電影《小時代》宣傳曲)",
        "tm": 247,
        "_id": "9011601",
        "type": "music",
        "dbIndex": 142,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 142
      },
      {
        "t": "yt",
        "f": "wFRONh6EPjQ",
        "tt": "[HD1080P] GEM鄧紫棋 - 單行的軌道 One Way Road DIYMV(5.1 Dolby pro surround KTV)",
        "tm": 249,
        "_id": "29356376",
        "type": "music",
        "dbIndex": 143,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 143
      },
      {
        "t": "yt",
        "f": "ewPA_GR3WFw",
        "tt": "阿媽的話",
        "tm": 289,
        "_id": "87150",
        "type": "music",
        "dbIndex": 144,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 144
      },
      {
        "t": "yt",
        "f": "QGhvc6v1ZAQ",
        "tt": "張碧晨 -《年輪》(電視劇花千骨插曲) ｜CC歌詞字幕",
        "tm": 275,
        "_id": "30154119",
        "type": "music",
        "dbIndex": 145,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 145
      },
      {
        "t": "yt",
        "f": "GaKq4jmNVwQ",
        "tt": "彭佳慧 Julia Peng《心之火 Xin Zhi Huo》ft. F.I.R.飛兒樂團 Music Video - 電視劇『花千骨』片頭曲",
        "tm": 281,
        "_id": "30171413",
        "type": "music",
        "dbIndex": 146,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 146
      },
      {
        "t": "yt",
        "f": "vBk9s8V3nq0",
        "tt": "A-Lin 黃麗玲《我等到花兒也謝了》-《我是歌手3》第五期",
        "tm": 338,
        "_id": "29787974",
        "type": "music",
        "dbIndex": 147,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 147
      },
      {
        "t": "yt",
        "f": "7RxvmTpnxzo",
        "tt": "迪克牛仔 - 披着羊皮的狼",
        "tm": 264,
        "_id": "9433291",
        "type": "music",
        "dbIndex": 148,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 148
      },
      {
        "t": "yt",
        "f": "RMc1S-WlMt0",
        "tt": "【披著羊皮的狼】刀郎",
        "tm": 450,
        "_id": "17928",
        "type": "music",
        "dbIndex": 149,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 149
      },
      {
        "t": "yt",
        "f": "SeD3rF_841M",
        "tt": "李琦 -《最長的旅途》(網劇無心法師片尾曲)",
        "tm": 228,
        "_id": "30362757",
        "type": "music",
        "dbIndex": 150,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 150
      },
      {
        "t": "yt",
        "f": "pPr8vkMAe9w",
        "tt": "動力火車 Power Station [ 無情的情書 Ruthless Love Letter ] Official Music Video",
        "tm": 308,
        "_id": "7539708",
        "type": "music",
        "dbIndex": 151,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 151
      },
      {
        "t": "yt",
        "f": "BznfL9FFHUc",
        "tt": "吳宗憲 -  三暝三日(320K高音質版)",
        "tm": 261,
        "_id": "30684984",
        "type": "music",
        "dbIndex": 152,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 152
      },
      {
        "t": "yt",
        "f": "3N4-Ig4XWUU",
        "tt": "I Am A Singer 3 episode 12  我是歌手3 第三季 第12期 2015-03-20  谭维维《乌兰巴托之夜》HD",
        "tm": 346,
        "_id": "29053260",
        "type": "music",
        "dbIndex": 153,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 153
      },
      {
        "t": "yt",
        "f": "lvDa3r1pNuE",
        "tt": "五月天 Mayday【擁抱 Embrace】Official Music Video",
        "tm": 258,
        "_id": "50232",
        "type": "music",
        "dbIndex": 154,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 154
      },
      {
        "t": "yt",
        "f": "XQl8NJceqjY",
        "tt": "动力火车 - 当 MV (動力火車-當-還珠格格主題曲)",
        "tm": 295,
        "_id": "137566",
        "type": "music",
        "dbIndex": 155,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 155
      },
      {
        "t": "yt",
        "f": "rzzul2fmufI",
        "tt": "G.E.M.【盲點 BLINDSPOT 】Official MV [HD] 鄧紫棋",
        "tm": 246,
        "_id": "32034332",
        "type": "music",
        "dbIndex": 156,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 156
      },
      {
        "t": "yt",
        "f": "85cQRWaQn7c",
        "tt": "蔡琴 - 油麻菜籽 / Brassica Napus (by Tsai Chin)",
        "tm": 223,
        "_id": "31358847",
        "type": "music",
        "dbIndex": 157,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 157
      },
      {
        "t": "yt",
        "f": "Wmb8twEjlgg",
        "tt": "謝霆鋒 Nicholas Tse《謝謝你的愛1999(國)》[Official MV]",
        "tm": 209,
        "_id": "5719411",
        "type": "music",
        "dbIndex": 158,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 158
      },
      {
        "t": "yt",
        "f": "i7SPaBDwxsI",
        "tt": "動力火車 尤秋興 [ 不完美心跳 Lost Heartbeat ] 歌詞版Music Video (偶像劇｢必娶女人｣插曲)",
        "tm": 273,
        "_id": "32705947",
        "type": "music",
        "dbIndex": 159,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 159
      },
      {
        "t": "yt",
        "f": "iK18_Hz7NLc",
        "tt": "Pitbull - International Love ft. Chris Brown 2012",
        "tm": 249,
        "_id": "7584892",
        "type": "music",
        "dbIndex": 160,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 160
      },
      {
        "t": "yt",
        "f": "i4wiZ4fZIDo",
        "tt": "Black Widow - Iggy Azalea feat. Rita Ora (LYRIC VIDEO)",
        "tm": 210,
        "_id": "25717127",
        "type": "music",
        "dbIndex": 161,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 161
      },
      {
        "t": "yt",
        "f": "cilKbr7ofAQ",
        "tt": "蕭敬騰 Jam Hsiao - 一次幸福的機會 The blessed moment (華納official 官方完整版MV)",
        "tm": 300,
        "_id": "32781587",
        "type": "music",
        "dbIndex": 162,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 162
      },
      {
        "t": "yt",
        "f": "pOWHClN5D78",
        "tt": "蕭敬騰 Jam Hsiao - 袖手旁觀 Without Doing Anything  (華納official 官方完整版MV)",
        "tm": 313,
        "_id": "33067322",
        "type": "music",
        "dbIndex": 163,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 163
      },
      {
        "t": "yt",
        "f": "XiBAK5S-ycA",
        "tt": "說什麼山盟海誓 MV",
        "tm": 303,
        "_id": "535541",
        "type": "music",
        "dbIndex": 164,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 164
      },
      {
        "t": "yt",
        "f": "CsTB6MAvYEU",
        "tt": "黄乙玲MTV－爱你无条件",
        "tm": 270,
        "_id": "86496",
        "type": "music",
        "dbIndex": 165,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 165
      },
      {
        "t": "yt",
        "f": "ovRb5Na2j7Y",
        "tt": "蕭敬騰新電影\"\"一路驚喜\"\"主題曲-到處都是愛",
        "tm": 225,
        "_id": "27865896",
        "type": "music",
        "dbIndex": 166,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 166
      },
      {
        "t": "yt",
        "f": "kyGa8BkLve4",
        "tt": "彭佳慧 Julia Peng - 陪他",
        "tm": 318,
        "_id": "31355427",
        "type": "music",
        "dbIndex": 167,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 167
      },
      {
        "t": "yt",
        "f": "Owe3Fjcf--g",
        "tt": "彭佳慧 Julia Peng《鏡子裡的我 The Reflection of Me》Music Video",
        "tm": 301,
        "_id": "29890519",
        "type": "music",
        "dbIndex": 168,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 168
      },
      {
        "t": "yt",
        "f": "hhbvQPQjraY",
        "tt": "彭佳慧 Julia Peng - 走在紅毯那一天",
        "tm": 267,
        "_id": "31103792",
        "type": "music",
        "dbIndex": 169,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 169
      },
      {
        "t": "yt",
        "f": "iBcUGsOJIO8",
        "tt": "蘇運瑩 & 田馥甄 - 野子",
        "tm": 228,
        "_id": "29240607",
        "type": "music",
        "dbIndex": 170,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 170
      },
      {
        "t": "yt",
        "f": "dEzCi4i16dA",
        "tt": "彭佳慧 Julia Peng - 回味",
        "tm": 300,
        "_id": "21246857",
        "type": "music",
        "dbIndex": 171,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 171
      },
      {
        "t": "yt",
        "f": "cB7DIIG0ykk",
        "tt": "蔡依林 Jolin Tsai - 倒帶",
        "tm": 265,
        "_id": "21213118",
        "type": "music",
        "dbIndex": 172,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 172
      },
      {
        "t": "yt",
        "f": "bDZ2pcn_V4c",
        "tt": "蕭煌奇 末班車完整版MV-華納official HQ官方版MV",
        "tm": 322,
        "_id": "11110",
        "type": "music",
        "dbIndex": 173,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 173
      },
      {
        "t": "yt",
        "f": "W4dOifzE6R4",
        "tt": "蕭煌奇 Ricky Xiao -上水的花 The Most Beautiful Flower (華納official 高畫質 HD 官方完整版MV)",
        "tm": 334,
        "_id": "25101289",
        "type": "music",
        "dbIndex": 174,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 174
      },
      {
        "t": "yt",
        "f": "sbn_9OMbv4o",
        "tt": "男人情女人心 - 龙千玉 VS 袁小迪",
        "tm": 246,
        "_id": "262602",
        "type": "music",
        "dbIndex": 175,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 175
      },
      {
        "t": "yt",
        "f": "OjRH4vSJovE",
        "tt": "李千娜 Nana Lee - 最愛的人 feat. 王大文 Dawen （Official MV 官方完整版）",
        "tm": 205,
        "_id": "34762128",
        "type": "music",
        "dbIndex": 176,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 176
      },
      {
        "t": "yt",
        "f": "nWb_X3ZJQjw",
        "tt": "五月天 Mayday【溫柔 Tenderness】Official Music Video",
        "tm": 271,
        "_id": "38150",
        "type": "music",
        "dbIndex": 177,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 177
      },
      {
        "t": "yt",
        "f": "b-QdoRKJF2A",
        "tt": "[完整版]G.E.M.鄧紫棋《If I Were A Boy》《我是歌手第二季》",
        "tm": 280,
        "_id": "23576743",
        "type": "music",
        "dbIndex": 178,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 178
      },
      {
        "t": "yt",
        "f": "jaRTTVwWNA4",
        "tt": "张靓颖 - 离歌 (我是歌手第三季, 优化版)",
        "tm": 312,
        "_id": "28377748",
        "type": "music",
        "dbIndex": 179,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 179
      },
      {
        "t": "yt",
        "f": "JvkqZrYJUe8",
        "tt": "玖壹壹(Nine one one)-嘻哈庄腳情 官方MV首播",
        "tm": 241,
        "_id": "33637296",
        "type": "music",
        "dbIndex": 180,
        "action": "editMusic",
        "currentListeningCount": 5,
        "musicIndex": 180
      },
      {
        "t": "yt",
        "f": "lKe0k2pF9pc",
        "tt": "UNDER LOVER - 癡情玫瑰花 ft 玖壹壹 春風 (官方Music video)",
        "tm": 283,
        "_id": "32891479",
        "type": "music",
        "dbIndex": 181,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 181
      },
      {
        "t": "yt",
        "f": "f2u9F-IT9wY",
        "tt": "玖壹壹(Nine one one)-下輩子 官方MV首播",
        "tm": 262,
        "_id": "33390350",
        "type": "music",
        "dbIndex": 182,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 182
      },
      {
        "t": "yt",
        "f": "DyW_RIiakgQ",
        "tt": "玖壹壹（Nine one one)回來我身邊 官方MV首播",
        "tm": 235,
        "_id": "35353299",
        "type": "music",
        "dbIndex": 183,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 183
      },
      {
        "t": "yt",
        "f": "mNMH7SLGDOw",
        "tt": "玖壹壹-我的路",
        "tm": 269,
        "_id": "31634135",
        "type": "music",
        "dbIndex": 184,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 184
      },
      {
        "t": "yt",
        "f": "QrtX2CKEx1g",
        "tt": "2013 徐承邦《媽祖的囝子》HD",
        "tm": 268,
        "_id": "18436893",
        "type": "music",
        "dbIndex": 185,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 185
      },
      {
        "t": "yt",
        "f": "VtPcc-52Fr8",
        "tt": "李佳薇 Jess Lee - 暴風雪 Snowstorm (華納 official HD 官方版MV)",
        "tm": 247,
        "_id": "35590402",
        "type": "music",
        "dbIndex": 186,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 186
      },
      {
        "t": "yt",
        "f": "kDOYTtM6RCQ",
        "tt": "A-Lin《‪幸福太短 / Fleeting Happiness》歌詞版 Lyric Video - 電視劇『奇妙的時光之旅』片尾曲 (Unofficial)",
        "tm": 255,
        "_id": "35649518",
        "type": "music",
        "dbIndex": 187,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 187
      },
      {
        "t": "yt",
        "f": "F6QjINLJPmI",
        "tt": "吳宗憲 Jacky Wu - 沒妳的城市",
        "tm": 277,
        "_id": "25429757",
        "type": "music",
        "dbIndex": 188,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 188
      },
      {
        "t": "yt",
        "f": "KqW14b50h3M",
        "tt": "周慧敏 Vivian Chow - 依靠 (官方版MV)",
        "tm": 255,
        "_id": "28202333",
        "type": "music",
        "dbIndex": 189,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 189
      },
      {
        "t": "yt",
        "f": "DyW_RIiakgQ",
        "tt": "玖壹壹（Nine one one)回來我身邊 官方MV首播",
        "tm": 235,
        "_id": "35353299",
        "type": "music",
        "dbIndex": 190,
        "action": "editMusic",
        "currentListeningCount": 3,
        "musicIndex": 190
      },
      {
        "t": "yt",
        "f": "UyeeFaTfMg8",
        "tt": "依稀 - 冰吻(超級好聽=][)",
        "tm": 246,
        "_id": "21036",
        "type": "music",
        "dbIndex": 191,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 191
      },
      {
        "t": "yt",
        "f": "_VxLOj3TB5k",
        "tt": "周杰倫Jay Chou X aMEI【不該 Shouldn't Be】Official MV",
        "tm": 294,
        "_id": "36508675",
        "type": "music",
        "dbIndex": 192,
        "action": "editMusic",
        "currentListeningCount": 11,
        "musicIndex": 192
      },
      {
        "t": "yt",
        "f": "1xlASR2bfGk",
        "tt": "薛之謙 Joker Xue【醜八怪】官方完整版 MV (曲: 李榮浩)",
        "tm": 243,
        "_id": "23521286",
        "type": "music",
        "dbIndex": 193,
        "action": "editMusic",
        "currentListeningCount": 11,
        "musicIndex": 193
      },
      {
        "t": "yt",
        "f": "G6KPdUmHnEk",
        "tt": "【单曲欣赏】《我想和你唱》第9期 20160702: 徐佳莹 陈银玲 熊猫组合 刘嘉《身骑白马》Come Sing with Me EP.9【湖南卫视官方超清版】",
        "tm": 257,
        "_id": "37667507",
        "type": "music",
        "dbIndex": 194,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 194
      },
      {
        "t": "yt",
        "f": "b_Gug5ljr5k",
        "tt": "【单曲欣赏】《我想和你唱》第8期 20160625: 任贤齐《天涯》Come Sing with Me EP.8【湖南卫视官方超清版】",
        "tm": 227,
        "_id": "36717270",
        "type": "music",
        "dbIndex": 195,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 195
      },
      {
        "t": "yt",
        "f": "bu2kWZHqgAQ",
        "tt": "【单曲欣赏】《我想和你唱》第5期 20160604: 信《死了都要爱》Come Sing with Me EP.5【湖南卫视官方超清版】",
        "tm": 248,
        "_id": "36291924",
        "type": "music",
        "dbIndex": 196,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 196
      },
      {
        "t": "yt",
        "f": "gq9mWtmNhdk",
        "tt": "【单曲欣赏】《我想和你唱》第8期 20160625: 曹格《背叛》Come Sing with Me EP.8【湖南卫视官方超清版】",
        "tm": 227,
        "_id": "36717258",
        "type": "music",
        "dbIndex": 197,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 197
      },
      {
        "t": "yt",
        "f": "t2fIwFXPk0Y",
        "tt": "【单曲欣赏】《我想和你唱》第2期 20160514: 黄丽玲《给我一个理由忘记》Come Sing with Me EP.2【湖南卫视官方超清版】",
        "tm": 206,
        "_id": "35914319",
        "type": "music",
        "dbIndex": 198,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 198
      },
      {
        "t": "yt",
        "f": "5CgYDVXNTnU",
        "tt": "【单曲欣赏】《我想和你唱》第7期 20160618: 费玉清 韩基男 吉鹏飞《一剪梅》Come Sing with Me EP.7【湖南卫视官方超清版】",
        "tm": 246,
        "_id": "36692876",
        "type": "music",
        "dbIndex": 199,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 199
      },
      {
        "t": "yt",
        "f": "Zgztpu4TizA",
        "tt": "【单曲欣赏】《我想和你唱》第6期 20160611: 林志炫 张亮 高霖寒 杨海峰《单身情歌》Come Sing with Me EP.6【湖南卫视官方超清版】",
        "tm": 207,
        "_id": "36400138",
        "type": "music",
        "dbIndex": 200,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 200
      },
      {
        "t": "yt",
        "f": "4BK-QwROCaU",
        "tt": "【单曲欣赏】《我想和你唱》第5期 20160604: 信《火烧的寂寞》Come Sing with Me EP.5【湖南卫视官方超清版】",
        "tm": 199,
        "_id": "36291926",
        "type": "music",
        "dbIndex": 201,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 201
      },
      {
        "t": "yt",
        "f": "XrXt1F5SwXg",
        "tt": "【单曲欣赏】《我想和你唱》第5期 20160604: 黄小琥《没那么简单》Come Sing with Me EP.5【湖南卫视官方超清版】",
        "tm": 223,
        "_id": "36278164",
        "type": "music",
        "dbIndex": 202,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 202
      },
      {
        "t": "yt",
        "f": "onLiS5zD4ts",
        "tt": "一剪梅 / 楊坤 旦增尼瑪 (最美和聲3 / 純歌曲版)",
        "tm": 229,
        "_id": "30596464",
        "type": "music",
        "dbIndex": 203,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 203
      },
      {
        "t": "yt",
        "f": "bLJw-xXcqCE",
        "tt": "散了吧 - 林志炫.wmv",
        "tm": 272,
        "_id": "64658",
        "type": "music",
        "dbIndex": 204,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 204
      },
      {
        "t": "yt",
        "f": "XKuL5xaKZHM",
        "tt": "薛之謙 Joker Xue【演員】官方完整版 MV",
        "tm": 299,
        "_id": "30134730",
        "type": "music",
        "dbIndex": 205,
        "action": "editMusic",
        "currentListeningCount": 24,
        "musicIndex": 205
      },
      {
        "t": "yt",
        "f": "1xlASR2bfGk",
        "tt": "薛之謙 Joker Xue【醜八怪】官方完整版 MV (曲: 李榮浩)",
        "tm": 243,
        "_id": "23521286",
        "type": "music",
        "dbIndex": 206,
        "action": "editMusic",
        "currentListeningCount": 11,
        "musicIndex": 206
      },
      {
        "t": "yt",
        "f": "19K2t5PS-Mk",
        "tt": "薛之謙 Joker Xue【我好像在哪見過你】官方完整版 MV",
        "tm": 299,
        "_id": "38442775",
        "type": "music",
        "dbIndex": 207,
        "action": "editMusic",
        "currentListeningCount": 10,
        "musicIndex": 207
      },
      {
        "t": "yt",
        "f": "Zy5bzmstORM",
        "tt": "20140221我是歌手第二季-張杰《無情的情書》 JasonZhang/ZhangJie -原唱 動力火車",
        "tm": 473,
        "_id": "23761471",
        "type": "music",
        "dbIndex": 208,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 208
      },
      {
        "t": "yt",
        "f": "ItJVkPuXsiw",
        "tt": "[ SOPCharts ][ C-POP ] 張杰 - 逆戰",
        "tm": 232,
        "_id": "91228",
        "type": "music",
        "dbIndex": 209,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 209
      },
      {
        "t": "yt",
        "f": "usFiJU0faOM",
        "tt": "張杰 Jason Zhang - 浮誅 (官方歌詞版) - 電視劇《青云志》片頭曲",
        "tm": 256,
        "_id": "39598099",
        "type": "music",
        "dbIndex": 210,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 210
      },
      {
        "t": "yt",
        "f": "hsUvFTXKoeo",
        "tt": "【单曲纯享版】项亚蕻《空空如也》 《中国新歌声》第6期 SING!CHINA EP.6 20160819 [浙江卫视官方超清1080P] 汪峰战队",
        "tm": 274,
        "_id": "39742097",
        "type": "music",
        "dbIndex": 211,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 211
      },
      {
        "t": "yt",
        "f": "jYm_L-51o8w",
        "tt": "黄绮珊 - 等待（立体声现场版）HD 高品质",
        "tm": 337,
        "_id": "7130458",
        "type": "music",
        "dbIndex": 212,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 212
      },
      {
        "t": "yt",
        "f": "9O_LircHbd8",
        "tt": "陳冰 -《一個人》｜歌詞字幕",
        "tm": 268,
        "_id": "41503992",
        "type": "music",
        "dbIndex": 213,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 213
      },
      {
        "t": "yt",
        "f": "WZjC-N3o44I",
        "tt": "杨坤Yangkun - 牧马人MV",
        "tm": 272,
        "_id": "2484110",
        "type": "music",
        "dbIndex": 214,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 214
      },
      {
        "t": "yt",
        "f": "rCubtRLatqE",
        "tt": "戴荃 -《悟空》",
        "tm": 201,
        "_id": "32891506",
        "type": "music",
        "dbIndex": 215,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 215
      },
      {
        "t": "yt",
        "f": "tNcLseWnYv4",
        "tt": "20150130 中国好歌曲第二季金曲 戴荃悟空",
        "tm": 197,
        "_id": "28744956",
        "type": "music",
        "dbIndex": 216,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 216
      },
      {
        "t": "yt",
        "f": "OsUr8N7t4zc",
        "tt": "Mayday五月天 feat.蕭敬騰 [ 凡人歌 Song of Ordinary People ] Official Music Video",
        "tm": 292,
        "_id": "45061342",
        "type": "music",
        "dbIndex": 217,
        "action": "editMusic",
        "currentListeningCount": 8,
        "musicIndex": 217
      },
      {
        "t": "yt",
        "f": "jJxkqAOXW1o",
        "tt": "陳盈潔 - 海海人生 / People Life, Ocean Wild (by Ying-Jie Chen)",
        "tm": 270,
        "_id": "379062",
        "type": "music",
        "dbIndex": 218,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 218
      },
      {
        "t": "yt",
        "f": "-ou_D0G50hc",
        "tt": "[純享版] A-Lin 黃麗玲 & 葉蒨文《愛的可能》獨唱 & 合唱【江蘇衛視 金曲撈 第七期】",
        "tm": 493,
        "_id": "50628296",
        "type": "music",
        "dbIndex": 219,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 219
      },
      {
        "t": "yt",
        "f": "qIF8xvSA0Gw",
        "tt": "黃明志Namewee ft. 王力宏 Leehom Wang【漂向北方 Stranger In The North 】@CROSSOVER ASIA 2017亞洲通車專輯",
        "tm": 312,
        "_id": "44695297",
        "type": "music",
        "dbIndex": 220,
        "action": "editMusic",
        "currentListeningCount": 20,
        "musicIndex": 220
      },
      {
        "t": "yt",
        "f": "-sM8SynMM5I",
        "tt": "兄弟本色 G.U.T.S【FLY OUT】Official Music Video",
        "tm": 265,
        "_id": "33442056",
        "type": "music",
        "dbIndex": 221,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 221
      },
      {
        "t": "yt",
        "f": "CPY6AML_GCY",
        "tt": "兄弟本色 G.U.T.S【迷途羔羊 Lost in Connection】Official Audio Video",
        "tm": 272,
        "_id": "34167329",
        "type": "music",
        "dbIndex": 222,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 222
      },
      {
        "t": "yt",
        "f": "29tEEaTN_Sc",
        "tt": "周湯豪 NICKTHEREAL《帥到分手》Official Music Video [飛魚高校生 片頭曲]",
        "tm": 228,
        "_id": "40841221",
        "type": "music",
        "dbIndex": 223,
        "action": "editMusic",
        "currentListeningCount": 6,
        "musicIndex": 223
      },
      {
        "t": "yt",
        "f": "Mxdgh6M0mPQ",
        "tt": "伍佰 Wu Bai&China Blue【殺手驪歌】Official Music Video",
        "tm": 286,
        "_id": "53099",
        "type": "music",
        "dbIndex": 224,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 224
      },
      {
        "t": "yt",
        "f": "EQI8oKA6X4o",
        "tt": "伍佰 Wu Bai&China Blue【斷腸詩 Broken heart poetry】Official Music Video",
        "tm": 215,
        "_id": "53092",
        "type": "music",
        "dbIndex": 225,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 225
      },
      {
        "t": "yt",
        "f": "QTvG5x1iKnk",
        "tt": "nicholas tse 謝霆鋒-要我怎麼忘了她MV HQ",
        "tm": 297,
        "_id": "177683",
        "type": "music",
        "dbIndex": 226,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 226
      },
      {
        "t": "yt",
        "f": "70TOodJza8w",
        "tt": "黃明志/不想上班 【歌詞版】",
        "tm": 324,
        "_id": "44258859",
        "type": "music",
        "dbIndex": 227,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 227
      },
      {
        "t": "yt",
        "f": "z68cteMx188",
        "tt": "林垂立 彭莉 - 感謝你的愛",
        "tm": 217,
        "_id": "41116437",
        "type": "music",
        "dbIndex": 228,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 228
      },
      {
        "t": "yt",
        "f": "kYg0QXCt3RQ",
        "tt": "【单曲纯享版】张杰《天上掉下个林妹妹》《天籁之战2》第2期【东方卫视官方高清】",
        "tm": 223,
        "_id": "70205573",
        "type": "music",
        "dbIndex": 229,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 229
      },
      {
        "t": "yt",
        "f": "CqLfUvTIHhY",
        "tt": "【音乐纯享版】跨界歌王第二季：谢娜、张杰《天下》",
        "tm": 236,
        "_id": "51345678",
        "type": "music",
        "dbIndex": 230,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 230
      },
      {
        "t": "yt",
        "f": "2pXXjBe1fXo",
        "tt": "大壯【我們不一樣】女生版 - 蔡佩軒 Ariel Tsai 翻唱",
        "tm": 252,
        "_id": "80811541",
        "type": "music",
        "dbIndex": 231,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 231
      },
      {
        "t": "yt",
        "f": "tMhZhcTygRU",
        "tt": "張韶涵 - 阿刁 (純音樂音量加強版)",
        "tm": 310,
        "_id": "81548450",
        "type": "music",
        "dbIndex": 232,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 232
      },
      {
        "t": "yt",
        "f": "FZSVQRLVFy0",
        "tt": "G.E.M.【我只在乎你】Queen of Hearts 世界巡演現場版[HD] 鄧紫棋",
        "tm": 277,
        "_id": "82840672",
        "type": "music",
        "dbIndex": 233,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 233
      },
      {
        "t": "yt",
        "f": "YJSpGXxkCqE",
        "tt": "黃明志Namewee ft. 鄧紫棋 G.E.M.【漂向北方 Stranger In The North 】KTV Version 包廂版",
        "tm": 269,
        "_id": "70026915",
        "type": "music",
        "dbIndex": 234,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 234
      },
      {
        "t": "yt",
        "f": "sg_WE0ToJjM",
        "tt": "于文文《體面》動態歌詞版  【前任3:再見前任 插曲】",
        "tm": 283,
        "_id": "81936788",
        "type": "music",
        "dbIndex": 235,
        "action": "editMusic",
        "currentListeningCount": 30,
        "musicIndex": 235
      },
      {
        "t": "yt",
        "f": "9O_LircHbd8",
        "tt": "陳冰 -《一個人》｜歌詞字幕",
        "tm": 268,
        "_id": "41503992",
        "type": "music",
        "dbIndex": 236,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 236
      },
      {
        "t": "yt",
        "f": "kn31FtSHlhw",
        "tt": "陳柯宇 - 生僻字 (繁體注音)(高音質)【動態歌詞Lyrics】",
        "tm": 217,
        "_id": "90208278",
        "type": "music",
        "dbIndex": 237,
        "action": "editMusic",
        "currentListeningCount": 4,
        "musicIndex": 237
      },
      {
        "t": "yt",
        "f": "sg_WE0ToJjM",
        "tt": "于文文《體面》動態歌詞版  【前任3:再見前任 插曲】",
        "tm": 283,
        "_id": "81936788",
        "type": "music",
        "dbIndex": 238,
        "action": "editMusic",
        "currentListeningCount": 30,
        "musicIndex": 238
      },
      {
        "t": "yt",
        "f": "Oa49Nym7wJk",
        "tt": "王貳浪 - 往後餘生（COVER 馬良）『心底溫柔是你，目光所致也是你。』【動態歌詞Lyrics】",
        "tm": 233,
        "_id": "85086016",
        "type": "music",
        "dbIndex": 239,
        "action": "editMusic",
        "currentListeningCount": 21,
        "musicIndex": 239
      },
      {
        "t": "yt",
        "f": "t_37MsrA9mo",
        "tt": "G.E.M 鄧紫棋【雨蝶】超好聽 Lyric Video 歌詞版 [HD] 張靚穎 鄧紫棋",
        "tm": 5012,
        "_id": "83410686",
        "type": "music",
        "dbIndex": 240,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 240
      },
      {
        "t": "yt",
        "f": "hikssnalypk",
        "tt": "【HD】許佳慧-預謀MV [Official Music Video]官方完整版",
        "tm": 245,
        "_id": "21858659",
        "type": "music",
        "dbIndex": 241,
        "action": "editMusic",
        "currentListeningCount": 1,
        "musicIndex": 241
      },
      {
        "t": "yt",
        "f": "q-c35Fqje3g",
        "tt": "代理仁《預謀》反正她都不难受  她只要自由",
        "tm": 241,
        "_id": "91063227",
        "type": "music",
        "dbIndex": 242,
        "action": "editMusic",
        "currentListeningCount": 55,
        "musicIndex": 242
      },
      {
        "t": "yt",
        "f": "hVlmlDwhpWY",
        "tt": "Ayo97 - 感謝你曾來過 ft.阿涵「高音質 x 動態歌詞 Lyrics」♪ SDPMusic ♪",
        "tm": 237,
        "_id": "102981629",
        "type": "music",
        "dbIndex": 243,
        "action": "editMusic",
        "currentListeningCount": 96,
        "musicIndex": 243
      },
      {
        "t": "yt",
        "f": "sSHoZ9XP9Ls",
        "tt": "廖士賢 江山有夢",
        "tm": 262,
        "_id": "100621148",
        "type": "music",
        "dbIndex": 244,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 244
      },
      {
        "t": "yt",
        "f": "yjWwfDW9IoA",
        "tt": "卓義峯 Yifeng Zhuo -〈再見煙火〉Goodbye Firework【豐華唱片official 官方MV】",
        "tm": 305,
        "_id": "87371510",
        "type": "music",
        "dbIndex": 245,
        "action": "editMusic",
        "currentListeningCount": 107,
        "musicIndex": 245
      },
      {
        "t": "yt",
        "f": "VwB9VOfmwdo",
        "tt": "沈文程-五月十一彼下埔(卡拉OK原版)",
        "tm": 259,
        "_id": "5683642",
        "type": "music",
        "dbIndex": 246,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 246
      },
      {
        "t": "yt",
        "f": "L8XqJCNhX68",
        "tt": "沈文程+張瀛仁 - 舊情也綿綿",
        "tm": 256,
        "_id": "7495218",
        "type": "music",
        "dbIndex": 247,
        "action": "editMusic",
        "currentListeningCount": 0,
        "musicIndex": 247
      },
      {
        "t": "yt",
        "f": "s5d1XSwXmww",
        "tt": "郁可唯《獨家記憶》",
        "tm": 288,
        "_id": "81849993",
        "type": "music",
        "dbIndex": 248,
        "action": "editMusic",
        "currentListeningCount": 2,
        "musicIndex": 248
      }
    ],
    "name": "胖輝輝",
    "owner": "5209966",
    "subsCnt": 1,
    "thumbnail": "https://i.ytimg.com/vi/TWWgQbbPnps/default.jpg",
    "thumbnailHQ": "https://i.ytimg.com/vi/TWWgQbbPnps/mqdefault.jpg",
    "itemCount": 249,
    "cover": "https://i.ytimg.com/vi/TWWgQbbPnps/default.jpg",
    "coverhq": "https://i.ytimg.com/vi/TWWgQbbPnps/mqdefault.jpg",
    "isAlbum": False,
    "ownerName": "張瞎輝",
    "total": 250,
    "trace": {
      "onReceiveResponse": [
        {
          "id": "playlistImpression",
          "arguments": {
            "api": "getVector",
            "isAlbum": False,
            "isSystem": False,
            "id": "7742969",
            "owner": "5209966",
            "containsSimilarPlaylists": False,
            "itemCount": 249
          }
        }
      ]
    }
  }
}